# Generated by Django 3.2.17 on 2023-02-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('secondary_phone_number', models.CharField(max_length=80)),
                ('job', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
