# Generated by Django 3.2.17 on 2023-02-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
