# Generated by Django 3.2.17 on 2023-02-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_auto_20230212_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.user'),
            preserve_default=False,
        ),
    ]
