# Generated by Django 3.2.17 on 2023-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20230212_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secondary_phone_number',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
