# Generated by Django 3.2.17 on 2023-02-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_auto_20230212_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contact', models.ManyToManyField(to='phonebook.Contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.user')),
            ],
        ),
    ]
